# 参照: https://runebook.dev/ja/docs/yarn/configuration/yarnrc

# 圧縮レベル（mixedでもOK、サイズと速度のバランス）
compressionLevel: mixed

# キャッシュをグローバルではなくプロジェクトごとに管理
enableGlobalCache: false

# Plug'n'Play を有効にする
nodeLinker: pnp
# nodeLinker: node-modules

# 一部の古いパッケージとの互換性確保
pnpMode: loose

# パッケージの解決に失敗したときのデバッグ用
pnpFallbackMode: dependencies-only

# zipの展開場所を .yarn/cache に固定（zipfs が苦手なツール向け）
# enableImmutableInstalls: true

# lockfile や .yarn/cache を変更したときにCIでエラーを出す
# enableImmutableCache: true

# CLI の出力を静かにする（不要なログを減らす）
logFilters:
  - code: YN0000
    level: discard